# Generated by Django 4.2.25 on 2025-11-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=50, unique=True)),
                (
                    "verification_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Private photo for verification only - never shown publicly",
                        null=True,
                        upload_to="verification_photos/",
                    ),
                ),
                (
                    "ghost_avatar",
                    models.ImageField(
                        default="ghost_avatars/1.png",
                        help_text="Public profile avatar",
                        upload_to="ghost_avatars/",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("ghost_level", models.IntegerField(default=1)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("github_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "haunted_profiles_user",
                "indexes": [
                    models.Index(
                        fields=["google_id"], name="haunted_pro_google__c3c667_idx"
                    ),
                    models.Index(
                        fields=["username"], name="haunted_pro_usernam_d555cf_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="haunted_pro_is_veri_f7150a_idx"
                    ),
                ],
            },
        ),
    ]
