# Generated by Django 4.2.25 on 2025-11-13 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="devpost_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_portfolio_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="portfolio_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI-analyzed skills and achievements",
            ),
        ),
        migrations.CreateModel(
            name="SummoningPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                (
                    "job_title",
                    models.CharField(
                        help_text="What role are you summoning?", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="What will they do?", max_length=2000),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        default=list, help_text="Skills needed (e.g., Python, React)"
                    ),
                ),
                ("location", models.CharField(help_text="Remote/City", max_length=200)),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, help_text="e.g., $60k-$80k", max_length=100
                    ),
                ),
                ("is_remote", models.BooleanField(default=True)),
                (
                    "no_degree_required",
                    models.BooleanField(
                        default=True, help_text="Self-taught devs welcome!"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GraveyardPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="What did you build?", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Tell us about it", max_length=1000),
                ),
                (
                    "code_snippet",
                    models.TextField(
                        blank=True, help_text="Paste your code (optional)"
                    ),
                ),
                (
                    "project_link",
                    models.URLField(blank=True, help_text="GitHub/Demo link"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="graveyard_posts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roast_score",
                    models.IntegerField(
                        default=0, help_text="How helpful are the roasts?"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graveyard_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GhostCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Crew name (e.g., 'The Python Haunters')",
                        max_length=100,
                    ),
                ),
                (
                    "crew_bio",
                    models.TextField(
                        blank=True, help_text="What's your crew about?", max_length=300
                    ),
                ),
                ("hackathons_won", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_crews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="crews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ghost Crews",
            },
        ),
        migrations.CreateModel(
            name="GhostChant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chant",
                    models.TextField(
                        help_text="Be honest - praise or constructive feedback!",
                        max_length=500,
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        default=False, help_text="Marked helpful by post author"
                    ),
                ),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chants",
                        to="haunted_profiles.graveyardpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=1000)),
                (
                    "is_code",
                    models.BooleanField(
                        default=False, help_text="Is this a code snippet?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="haunted_profiles.ghostcrew",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_message",
                    models.TextField(
                        help_text="Why should they summon you?", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("summoned", "Summoned! (Hired)"),
                            ("rejected", "Not This Time"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="haunted_profiles.summoningpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="CrewInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Why should they join?", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "crew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="haunted_profiles.ghostcrew",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("crew", "to_user")},
            },
        ),
    ]
