# Generated by Django 4.2.25 on 2025-11-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "haunted_profiles",
            "0002_user_devpost_url_user_last_portfolio_update_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coding_journey",
            field=models.TextField(
                blank=True, help_text="Your coding journey and what you are learning"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="core_skills",
            field=models.TextField(
                blank=True,
                help_text="Your main skills (e.g., Object Detection, SGAN, PyTorch, React)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="developer_role",
            field=models.CharField(
                blank=True,
                help_text="What you do (e.g., Computer Vision Developer, Full Stack Engineer)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="strengths",
            field=models.TextField(
                blank=True,
                help_text="What you are good at (e.g., ML algorithms, backend optimization)",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weaknesses",
            field=models.TextField(
                blank=True,
                help_text="What you use AI help for (e.g., UI/UX, Streamlit, CSS styling)",
            ),
        ),
    ]
