# Generated by Django 4.2.25 on 2025-11-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_profiles", "0003_user_coding_journey_user_core_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_usage_context",
            field=models.TextField(
                blank=True, help_text="Where and how you use AI in your workflow"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="expertise_area",
            field=models.CharField(
                blank=True,
                help_text="Primary expertise (e.g., Computer Vision, Backend Engineering)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="expertise_details",
            field=models.TextField(
                blank=True, help_text="What you know in your expertise area"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="learning_journey",
            field=models.TextField(
                blank=True, help_text="Your learning path and growth story"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="non_expertise_areas",
            field=models.TextField(
                blank=True, help_text="Areas where you rely on AI (e.g., UI/UX, DevOps)"
            ),
        ),
    ]
