# Generated by Django 4.2.25 on 2025-11-17 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("haunted_profiles", "0005_connection_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_company",
            field=models.BooleanField(
                default=False, help_text="Is this user a company account?"
            ),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "files",
                    models.FileField(
                        blank=True,
                        help_text="Uploaded files/code",
                        null=True,
                        upload_to="submissions/",
                    ),
                ),
                (
                    "code_text",
                    models.TextField(blank=True, help_text="Code or text submission"),
                ),
                (
                    "github_link",
                    models.URLField(
                        blank=True, help_text="GitHub repository link", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes for company"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True, help_text="Rating from 1-5 stars", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Feedback from company", null=True
                    ),
                ),
                (
                    "public_feedback",
                    models.BooleanField(
                        default=False, help_text="Show feedback on profile"
                    ),
                ),
                ("rated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission",
                        to="haunted_profiles.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("paid_trial", "Paid Trial"),
                            ("internship", "Internship"),
                            ("skill_challenge", "Skill Challenge"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "skills_needed",
                    models.JSONField(default=list, help_text="List of required skills"),
                ),
                (
                    "full_job_details",
                    models.TextField(
                        blank=True, help_text="Full job description if successful"
                    ),
                ),
                (
                    "payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "time_limit_hours",
                    models.IntegerField(
                        blank=True, help_text="Time limit in hours", null=True
                    ),
                ),
                (
                    "success_criteria",
                    models.TextField(
                        blank=True, help_text="What defines success", null=True
                    ),
                ),
                (
                    "duration_months",
                    models.IntegerField(
                        blank=True, help_text="Duration in months (1-6)", null=True
                    ),
                ),
                (
                    "stipend_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monthly stipend (₹0 if unpaid)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="Day-to-day responsibilities", null=True
                    ),
                ),
                (
                    "conversion_potential",
                    models.BooleanField(
                        default=False, help_text="Can lead to full-time role"
                    ),
                ),
                (
                    "challenge_description",
                    models.TextField(
                        blank=True, help_text="Challenge details", null=True
                    ),
                ),
                (
                    "dataset_file",
                    models.FileField(
                        blank=True,
                        help_text="Dataset or requirements file",
                        null=True,
                        upload_to="challenge_datasets/",
                    ),
                ),
                (
                    "dataset_link",
                    models.URLField(
                        blank=True, help_text="Link to dataset/requirements", null=True
                    ),
                ),
                (
                    "submission_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Submission deadline", null=True
                    ),
                ),
                (
                    "public_rating",
                    models.BooleanField(
                        default=False, help_text="Will publicly rate all submissions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invitation",
            name="developer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trial_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="haunted_profiles.opportunity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("opportunity", "developer")},
        ),
    ]
