# Generated by Django 4.2.25 on 2025-11-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "haunted_profiles",
            "0006_invitation_user_is_company_submission_opportunity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="haunted_profiles.invitation",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("connection_request", "Connection Request"),
                    ("connection_accepted", "Connection Accepted"),
                    ("connection_rejected", "Connection Rejected"),
                    ("invitation_received", "Invitation Received"),
                    ("invitation_accepted", "Invitation Accepted"),
                    ("invitation_declined", "Invitation Declined"),
                    ("submission_received", "Submission Received"),
                    ("submission_rated", "Submission Rated"),
                    ("deadline_approaching", "Deadline Approaching"),
                ],
                max_length=30,
            ),
        ),
    ]
